application: openid-provider-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
  secure: always

- url: .*
  script: provider.application
  secure: always
